const fs = require('fs');

let engineCode = "// Neural Web Interactive Mouse Effect (Overlay Version)\n";
engineCode += "document.addEventListener('DOMContentLoaded', () => {\n";
engineCode += "    const isMobile = /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent) || window.innerWidth < 768;\n";
engineCode += "    const pCanvas = document.createElement('canvas'); \n";
engineCode += "    Object.assign(pCanvas.style, { position: 'fixed', top: '0', left: '0', width: '100vw', height: '100vh', zIndex: '-1', pointerEvents: 'none' }); \n";
engineCode += "    document.body.appendChild(pCanvas);\n";
engineCode += "    const ctx = pCanvas.getContext('2d');\n";
engineCode += "    let w, h;\n";
engineCode += "    function resize() { w = pCanvas.width = window.innerWidth; h = pCanvas.height = window.innerHeight; }\n";
engineCode += "    window.addEventListener('resize', resize); resize();\n";
engineCode += "    const maxParticles = isMobile ? 30 : 70; \n";
engineCode += "    const particles = [];\n";
engineCode += "    class Particle { \n";
engineCode += "        constructor(x, y, isStatic = false) { \n";
engineCode += "            this.x = x; this.y = y; this.isStatic = isStatic;\n";
engineCode += "            this.size = Math.random() * 2 + 1; \n";
engineCode += "            this.vx = (Math.random() - 0.5) * 1.5; \n";
engineCode += "            this.vy = (Math.random() - 0.5) * 1.5; \n";
engineCode += "            this.life = 1.0; \n";
engineCode += "        } \n";
engineCode += "        update() { \n";
engineCode += "            if(!this.isStatic) { this.x += this.vx; this.y += this.vy; this.life -= 0.005; }\n";
engineCode += "        } \n";
engineCode += "        draw() { \n";
engineCode += "            ctx.fillStyle = 'rgba(255, 255, 255, ' + (this.life * 0.4) + ')'; \n";
engineCode += "            ctx.beginPath(); ctx.arc(this.x, this.y, this.size, 0, Math.PI * 2); ctx.fill(); \n";
engineCode += "        } \n";
engineCode += "    }\n";
engineCode += "    function spawn(x, y) { \n";
engineCode += "        if(particles.length < maxParticles) particles.push(new Particle(x, y)); \n";
engineCode += "    }\n";
engineCode += "    window.addEventListener('mousemove', e => { spawn(e.clientX, e.clientY); });\n";
engineCode += "    window.addEventListener('touchmove', e => { if(e.touches.length > 0) spawn(e.touches[0].clientX, e.touches[0].clientY); }, { passive: true });\n";
engineCode += "    function animate() { \n";
engineCode += "        requestAnimationFrame(animate); \n";
engineCode += "        ctx.clearRect(0, 0, w, h);\n";
engineCode += "        for (let i = 0; i < particles.length; i++) { \n";
engineCode += "            particles[i].update(); \n";
engineCode += "            if (particles[i].life <= 0) { particles.splice(i, 1); i--; continue; } \n";
engineCode += "            particles[i].draw();\n";
engineCode += "            for (let j = i + 1; j < particles.length; j++) { \n";
engineCode += "                const dx = particles[i].x - particles[j].x, dy = particles[i].y - particles[j].y, dist = Math.sqrt(dx * dx + dy * dy);\n";
engineCode += "                if (dist < 120) { \n";
engineCode += "                    ctx.beginPath(); \n";
engineCode += "                    ctx.strokeStyle = 'rgba(255, 255, 255, ' + ((1 - dist / 120) * 0.3 * particles[i].life) + ')'; \n";
engineCode += "                    ctx.lineWidth = 0.6; \n";
engineCode += "                    ctx.moveTo(particles[i].x, particles[i].y); \n";
engineCode += "                    ctx.lineTo(particles[j].x, particles[j].y); \n";
engineCode += "                    ctx.stroke(); \n";
engineCode += "                } \n";
engineCode += "            } \n";
engineCode += "        } \n";
engineCode += "    }\n";
engineCode += "    animate();\n";
engineCode += "});\n";

fs.writeFileSync('c:/Users/user/Desktop/baber123123/assets/engine.js', engineCode);
console.log("Mouse-only Neural Web deployed, keeping original background intact.");
